id: '159'
name: Chantown Creative
locales:
  - en
themeHue: 190
domain: null
internalDomain: nameless-star-6618.admin.datocms.com
noIndex: false
globalSeo: null
favicon: null
faviconMetaTags:
  - tagName: meta
    attributes:
      name: application-name
      content: Chantown Creative