  # machine:
  #   node:
  #     version: 0.10.22
  #
  # dependencies:
  #   override:
  #     # if your project uses Yarn as package manager, replace "npm install" with "yarn"
  #     - npm install
  #     - npm install gulp -g
  # test:
  #   override:
  #     # runs tasks to grab data from DatoCMS, compile SCSS, JS and create a built site from the handlebars templates
  #     - gulp build
  # deployment:
  #   staging:
  #     branch: master
  #     commands:
  #       # task that sends the site to chantown.com/newwebtest
  #       - gulp deploy-to-staging
  #

version: 2
jobs:
  build:
    # working_directory: ~/mern-starter
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: prcess ticks
          command: npm install -g process-nextick-args
      - run:
          name: Install npm wee
          command: npm install
      - run:
          name: install gulp
          command: npm install -g gulp
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Build with gulp
          command: gulp build
      # - run:
      #     name: Generate code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
