  # machine:
  #   node:
  #     version: 0.10.22
  #
  # dependencies:
  #   override:
  #     # if your project uses Yarn as package manager, replace "npm install" with "yarn"
  #     - npm install
  #     - npm install gulp -g
  # test:
  #   override:
  #     # runs tasks to grab data from DatoCMS, compile SCSS, JS and create a built site from the handlebars templates
  #     - gulp build
  # deployment:
  #   staging:
  #     branch: master
  #     commands:
  #       # task that sends the site to chantown.com/newwebtest
  #       - gulp deploy-to-staging
  #


# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install gulp
          command: npm install gulp -g

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      run tests!
      - run:
          name: build the site
          command: gulp build
