# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chantown Creative
description: > #
  A creative communications agency that can help you with a wide range of copywriting, editing and custom publishing services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chantown.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
# sass:
#   add_charset: true
#   sass_dir: assets/sass
#   style: :compressed
#   includePaths: bourbon
#   includePaths: neat

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap



# settings to grab gallery and page data from contentful
contentful:
  spaces:
    - portfolio: # Jekyll _data folder identifier - Required
        space: nsozihf13xb6        # Required
        access_token: b8ce293104b3e00741c9db0132666bffef007e08af02bed03bfcc5866fe169f4 # Required
        cda_query:                 # Optional
          include: 10
          limit: 1000
        content_types:             # Optional
           cat: MyCoolMapper
        # client_options:            # Optional
        #   api_url: 'preview.contentful.com' # Defaults to 'api.contentful.com' which is Production
